---
version: "3.8"

services:
  bot:
    hostname: bot
    build: 
      context: ./bot
      args:
        BOT_TOKEN: ${BOT_TOKEN}
    container_name: bot
    restart: always
    depends_on:
      - psql

    networks:
      acu_net:
        ipv4_address: 172.72.72.3

  psql:
    hostname: psql
    build: 
      context: ./psql
      args:
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_PASSWD: ${POSTGRES_PASSWD}
    container_name: psql
    restart: always
    volumes:
      - psql:/var/lib/postgresql
    ports:
      - "5432:5432"
    networks:
      acu_net:
        ipv4_address: 172.72.72.2

  acunetix:
    # admin@admin.com
    # Admin123
    image: secfa/awvs
    init: true
    container_name: acunetix
    restart: unless-stopped
    cap_add:
      - LINUX_IMMUTABLE
    ports:
      - "3443:3443"

volumes:
  psql:

networks:
  acu_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.72.72.0/16
          gateway: 172.72.72.1