services:
  bot:
    hostname: bot
    container_name: bot
    build: 
      context: ./bot
    environment:
        BOT_TOKEN: ${BOT_TOKEN}
    restart: always
    depends_on:
      - psql

    networks:
      acu_net:
        ipv4_address: 172.72.72.4

  psql:
    hostname: psql
    image: postgres:14
    container_name: psql
    restart: on-failure
    volumes:
      - psql:/var/lib/postgresql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWD}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: Europe/Moscow

    networks:
      acu_net:
        ipv4_address: 172.72.72.2


  acunetix:
    hostname: acunetix
    container_name: acunetix
    build: 
      context: ./acunetix
    restart: unless-stopped
    cap_add:
      - LINUX_IMMUTABLE
    ports:
      - "13443:3443"
    environment:
      - ACUNETIX_EMAIL=${ACUNETIX_EMAIL}
      - ACUNETIX_PASSWORD=${ACUNETIX_PASSWORD}
      - MAIN_POSTGRES_DB=${POSTGRES_DB}
      - MAIN_POSTGRES_PASSWORD=${POSTGRES_PASSWD}
    networks:
      acu_net:
        ipv4_address: 172.72.72.3





volumes:
  psql:

networks:
  acu_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.72.72.0/24
          gateway: 172.72.72.1